package compact

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// bulkyKimiKeys are string fields whose value is conversation or payload
// content safe to truncate. Identifiers, types, names, roles and timestamps are
// intentionally excluded so event and tool-call linkage survives compaction.
var bulkyKimiKeys = map[string]bool{
	"text": true, "think": true, "thinking": true,
	"content": true, "arguments": true, "output": true,
	"input_text": true, "output_text": true, "data": true,
	"command": true, "stdout": true, "stderr": true, "error": true,
}

// deepKimiKeys mark subtrees carrying arbitrary tool input/output. Every string
// beneath them is truncatable regardless of its own key name.
var deepKimiKeys = map[string]bool{
	"args": true, "result": true, "return_value": true,
}

// compactKimiLine truncates the bulky content of one kimi-code wire entry while
// preserving its event structure, tool-call IDs and timestamps. It handles both
// context.append_message (message.content/toolCalls) and context.append_loop_event
// (event.part/args/result) shapes by walking the decoded entry recursively.
func compactKimiLine(entry map[string]any, threshold int64) int64 {
	return compactKimiNode(entry, threshold, false)
}

func compactKimiNode(v any, threshold int64, deep bool) int64 {
	switch t := v.(type) {
	case map[string]any:
		var saved int64
		for k, child := range t {
			childDeep := deep || deepKimiKeys[k]
			if s, ok := child.(string); ok {
				if deep || bulkyKimiKeys[k] {
					th := threshold
					if k == "think" || k == "thinking" {
						th *= 2
					}
					if newVal, delta := truncateString(s, th); delta > 0 {
						t[k] = newVal
						saved += delta
					}
				}
				continue
			}
			saved += compactKimiNode(child, threshold, childDeep)
		}
		return saved
	case []any:
		var saved int64
		for i, child := range t {
			if s, ok := child.(string); ok {
				if deep {
					if newVal, delta := truncateString(s, threshold); delta > 0 {
						t[i] = newVal
						saved += delta
					}
				}
				continue
			}
			saved += compactKimiNode(child, threshold, deep)
		}
		return saved
	}
	return 0
}

// kimiJSONLFiles returns every agent wire stream in a kimi-code session
// directory: the main agent plus any subagents under agents/<id>/wire.jsonl.
func kimiJSONLFiles(dir string) []string {
	matches, _ := filepath.Glob(filepath.Join(dir, "agents", "*", "wire.jsonl"))
	return matches
}

// kimiRawOutputs returns raw subagent output sidecars, truncated wholesale
// rather than line-by-line.
func kimiRawOutputs(dir string) []string {
	matches, _ := filepath.Glob(filepath.Join(dir, "agents", "*", "output"))
	return matches
}

// kimiLiveDirBytes returns the total size of a Kimi session directory,
// excluding backup/temp sidecars generated by compact.
func kimiLiveDirBytes(dir string) int64 {
	var total int64
	_ = filepath.WalkDir(dir, func(_ string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		name := d.Name()
		if filepath.Ext(name) == ".bak" || strings.HasSuffix(name, ".compact.tmp") {
			return nil
		}
		if info, err := d.Info(); err == nil {
			total += info.Size()
		}
		return nil
	})
	return total
}

func compactKimiSession(dir string, threshold int64, backup bool) (int64, error) {
	if err := guardPath(dir); err != nil {
		return 0, err
	}
	for _, path := range kimiJSONLFiles(dir) {
		if _, err := rewriteFile(path, compactKimiLine, threshold, backup); err != nil {
			return 0, fmt.Errorf("%s: %w", relKimiPath(dir, path), err)
		}
	}
	for _, path := range kimiRawOutputs(dir) {
		if err := compactKimiRawOutput(path, threshold, backup); err != nil {
			return 0, fmt.Errorf("%s: %w", relKimiPath(dir, path), err)
		}
	}
	return kimiLiveDirBytes(dir), nil
}

func compactKimiRawOutput(path string, threshold int64, backup bool) error {
	if err := guardPath(path); err != nil {
		return err
	}
	info, err := os.Stat(path)
	if err != nil {
		return err
	}
	if info.Size() <= threshold {
		return nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	newVal, delta := truncateString(string(data), threshold)
	if delta <= 0 {
		return nil
	}
	if backup {
		if err := copyFile(path, path+".bak"); err != nil {
			return fmt.Errorf("backup: %w", err)
		}
	}
	return os.WriteFile(path, []byte(newVal), info.Mode())
}

// estimateKimiSession simulates Kimi directory compaction without writing.
func estimateKimiSession(dir string, threshold int64) (int64, error) {
	total := kimiLiveDirBytes(dir)
	for _, path := range kimiJSONLFiles(dir) {
		info, err := os.Stat(path)
		if err != nil {
			continue
		}
		after, err := estimateJSONL(path, compactKimiLine, threshold)
		if err != nil {
			continue
		}
		total -= info.Size() - after
	}
	for _, path := range kimiRawOutputs(dir) {
		info, err := os.Stat(path)
		if err != nil || info.Size() <= threshold {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if newVal, delta := truncateString(string(data), threshold); delta > 0 {
			total -= info.Size() - int64(len(newVal))
		}
	}
	return total, nil
}

func relKimiPath(dir, path string) string {
	rel, err := filepath.Rel(dir, path)
	if err != nil {
		return filepath.Base(path)
	}
	return rel
}
