// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ReportView is the render-ready projection of a Report.
 */
export class ReportView {
    "Provider": string;
    "Source": string;
    "Note": string;
    "Windows": WindowView[];

    /** Creates a new ReportView instance. */
    constructor($$source: Partial<ReportView> = {}) {
        if (!("Provider" in $$source)) {
            this["Provider"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("Note" in $$source)) {
            this["Note"] = "";
        }
        if (!("Windows" in $$source)) {
            this["Windows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportView instance from a string or object.
     */
    static createFrom($$source: any = {}): ReportView {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Windows" in $$parsedSource) {
            $$parsedSource["Windows"] = $$createField3_0($$parsedSource["Windows"]);
        }
        return new ReportView($$parsedSource as Partial<ReportView>);
    }
}

/**
 * Severity is a style-free classification both UIs map to colors.
 */
export enum Severity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * neutral text
     */
    SevDefault = "default",

    /**
     * green
     */
    SevOK = "ok",

    /**
     * blue/primary
     */
    SevInfo = "info",

    /**
     * orange
     */
    SevWarn = "warn",

    /**
     * red
     */
    SevDanger = "danger",
};

export class SummaryCell {
    "Present": boolean;
    "UsedPercent": number;
    "ExpectedPercent": number;
    "Severity": Severity;

    /**
     * "21.0% used / 40.0% exp" or "--"
     */
    "Text": string;

    /** Creates a new SummaryCell instance. */
    constructor($$source: Partial<SummaryCell> = {}) {
        if (!("Present" in $$source)) {
            this["Present"] = false;
        }
        if (!("UsedPercent" in $$source)) {
            this["UsedPercent"] = 0;
        }
        if (!("ExpectedPercent" in $$source)) {
            this["ExpectedPercent"] = 0;
        }
        if (!("Severity" in $$source)) {
            this["Severity"] = Severity.$zero;
        }
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SummaryCell instance from a string or object.
     */
    static createFrom($$source: any = {}): SummaryCell {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SummaryCell($$parsedSource as Partial<SummaryCell>);
    }
}

export class SummaryRow {
    /**
     * short name: "Claude", "Kimi", ...
     */
    "Provider": string;
    "FiveHour": SummaryCell;
    "WeekGlobal": SummaryCell;

    /** Creates a new SummaryRow instance. */
    constructor($$source: Partial<SummaryRow> = {}) {
        if (!("Provider" in $$source)) {
            this["Provider"] = "";
        }
        if (!("FiveHour" in $$source)) {
            this["FiveHour"] = (new SummaryCell());
        }
        if (!("WeekGlobal" in $$source)) {
            this["WeekGlobal"] = (new SummaryCell());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SummaryRow instance from a string or object.
     */
    static createFrom($$source: any = {}): SummaryRow {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("FiveHour" in $$parsedSource) {
            $$parsedSource["FiveHour"] = $$createField1_0($$parsedSource["FiveHour"]);
        }
        if ("WeekGlobal" in $$parsedSource) {
            $$parsedSource["WeekGlobal"] = $$createField2_0($$parsedSource["WeekGlobal"]);
        }
        return new SummaryRow($$parsedSource as Partial<SummaryRow>);
    }
}

/**
 * View is the complete, UI-agnostic limits payload consumed by the TUI and GUI.
 */
export class View {
    "Reports": ReportView[];
    "Summary": SummaryRow[];
    "Available": boolean;

    /** Creates a new View instance. */
    constructor($$source: Partial<View> = {}) {
        if (!("Reports" in $$source)) {
            this["Reports"] = [];
        }
        if (!("Summary" in $$source)) {
            this["Summary"] = [];
        }
        if (!("Available" in $$source)) {
            this["Available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new View instance from a string or object.
     */
    static createFrom($$source: any = {}): View {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Reports" in $$parsedSource) {
            $$parsedSource["Reports"] = $$createField0_0($$parsedSource["Reports"]);
        }
        if ("Summary" in $$parsedSource) {
            $$parsedSource["Summary"] = $$createField1_0($$parsedSource["Summary"]);
        }
        return new View($$parsedSource as Partial<View>);
    }
}

/**
 * WindowView is a fully-computed, render-ready window (no styling, no time.Time).
 */
export class WindowView {
    "Label": string;
    "UsedPercent": number;

    /**
     * linear pace for elapsed window time
     */
    "ExpectedPercent": number;

    /**
     * "underutilizing" | "on track" | "overutilizing"
     */
    "PaceLabel": string;
    "PaceRatio": number;
    "PaceKnown": boolean;
    "UsedSeverity": Severity;

    /**
     * "in 3h 17m" / "" if unknown
     */
    "ResetRelative": string;

    /**
     * "Thu 30 Apr 20:10 CEST" / ""
     */
    "ResetAbsolute": string;

    /**
     * 0 if unknown
     */
    "ResetUnix": number;

    /** Creates a new WindowView instance. */
    constructor($$source: Partial<WindowView> = {}) {
        if (!("Label" in $$source)) {
            this["Label"] = "";
        }
        if (!("UsedPercent" in $$source)) {
            this["UsedPercent"] = 0;
        }
        if (!("ExpectedPercent" in $$source)) {
            this["ExpectedPercent"] = 0;
        }
        if (!("PaceLabel" in $$source)) {
            this["PaceLabel"] = "";
        }
        if (!("PaceRatio" in $$source)) {
            this["PaceRatio"] = 0;
        }
        if (!("PaceKnown" in $$source)) {
            this["PaceKnown"] = false;
        }
        if (!("UsedSeverity" in $$source)) {
            this["UsedSeverity"] = Severity.$zero;
        }
        if (!("ResetRelative" in $$source)) {
            this["ResetRelative"] = "";
        }
        if (!("ResetAbsolute" in $$source)) {
            this["ResetAbsolute"] = "";
        }
        if (!("ResetUnix" in $$source)) {
            this["ResetUnix"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowView instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowView($$parsedSource as Partial<WindowView>);
    }
}

// Private type creation functions
const $$createType0 = WindowView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = SummaryCell.createFrom;
const $$createType3 = ReportView.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SummaryRow.createFrom;
const $$createType6 = $Create.Array($$createType5);
